CREATE TABLE T_CT_AVALIACAO
    (
     CD_AVALIACAO  NUMBER (6)  NOT NULL ,
     NT_AVALIACAO  NUMBER (2,1)  NOT NULL ,
     DS_COMENTARIO VARCHAR2 (150 CHAR) ,
     DT_AVALIACAO  DATE  NOT NULL ,
     CD_USUARIO    NUMBER (6)  NOT NULL ,
     CD_PROJETO    NUMBER (6)  NOT NULL
    )
;

ALTER TABLE T_CT_AVALIACAO
    ADD CONSTRAINT PK_CT_AVALIACAO PRIMARY KEY ( CD_AVALIACAO ) ;

CREATE TABLE T_CT_COLABORACAO
    (
     CD_COLABORACAO NUMBER (6)  NOT NULL ,
     DT_ENTRADA     DATE  NOT NULL ,
     DS_FUNCAO      VARCHAR2 (60 CHAR)  NOT NULL ,
     CD_USUARIO     NUMBER (6)  NOT NULL ,
     CD_PROJETO     NUMBER (6)  NOT NULL
    )
;

ALTER TABLE T_CT_COLABORACAO
    ADD CONSTRAINT PK_CT_COLABORACAO PRIMARY KEY ( CD_COLABORACAO ) ;

CREATE TABLE T_CT_MENSAGEM
    (
     CD_MENSAGEM NUMBER (6)  NOT NULL ,
     DS_CONTEUDO VARCHAR2 (150)  NOT NULL ,
     DT_ENVIO    DATE  NOT NULL ,
     CD_USUARIO  NUMBER (6)  NOT NULL ,
     CD_PROJETO  NUMBER (6)  NOT NULL
    )
;

ALTER TABLE T_CT_MENSAGEM
    ADD CONSTRAINT PK_CT_MENSAGEM PRIMARY KEY ( CD_MENSAGEM ) ;

CREATE TABLE T_CT_PROJETO
    (
     CD_PROJETO  NUMBER (6)  NOT NULL ,
     DS_CONTEUDO VARCHAR2 (50 CHAR)  NOT NULL ,
     DT_ENTRADA  DATE  NOT NULL ,
     CD_USUARIO  NUMBER (6)  NOT NULL
    )
;

ALTER TABLE T_CT_PROJETO
    ADD CONSTRAINT PK_CT_PROJETO PRIMARY KEY ( CD_PROJETO ) ;

CREATE TABLE T_CT_TAREFA
    (
     CD_TAREFA    NUMBER (6)  NOT NULL ,
     NM_TAREFA    VARCHAR2 (100 CHAR)  NOT NULL ,
     DS_TAREFA    VARCHAR2 (120 CHAR)  NOT NULL ,
     DS_AREA      VARCHAR2 (80 CHAR)  NOT NULL ,
     DS_STATUS    VARCHAR2 (40 CHAR)  NOT NULL ,
     DT_CRIACAO   DATE  NOT NULL ,
     DT_CONCLUSAO DATE ,
     CD_PROJETO   NUMBER (6)  NOT NULL
    )
;

ALTER TABLE T_CT_TAREFA
    ADD CONSTRAINT PK_CT_TAREFA PRIMARY KEY ( CD_TAREFA ) ;

CREATE TABLE T_CT_USUARIO
    (
     CD_USUARIO    NUMBER (6)  NOT NULL ,
     NM_USUARIO    VARCHAR2 (80 CHAR)  NOT NULL ,
     DS_EMAIL      VARCHAR2 (60 CHAR)  NOT NULL ,
     DS_PAIS       VARCHAR2 (45 CHAR)  NOT NULL ,
     DS_IDIOMA     VARCHAR2 (60 CHAR)  NOT NULL ,
     TP_USUARIO    VARCHAR2 (30 CHAR)  NOT NULL ,
     DS_HABILIDADE VARCHAR2 (200 CHAR)  NOT NULL ,
     DT_CADASTRO   DATE  NOT NULL
    )
;

ALTER TABLE T_CT_USUARIO
    ADD CONSTRAINT PK_CT_USUARIO PRIMARY KEY ( CD_USUARIO ) ;

ALTER TABLE T_CT_AVALIACAO
    ADD CONSTRAINT FK_CT_AVALIACAO_PROJETO FOREIGN KEY
    (
     CD_PROJETO
    )
    REFERENCES T_CT_PROJETO
    (
     CD_PROJETO
    )
;

ALTER TABLE T_CT_AVALIACAO
    ADD CONSTRAINT FK_CT_AVALIACAO_USUARIO FOREIGN KEY
    (
     CD_USUARIO
    )
    REFERENCES T_CT_USUARIO
    (
     CD_USUARIO
    )
;

ALTER TABLE T_CT_COLABORACAO
    ADD CONSTRAINT FK_CT_COLABORACAO_PROJETO FOREIGN KEY
    (
     CD_PROJETO
    )
    REFERENCES T_CT_PROJETO
    (
     CD_PROJETO
    )
;

ALTER TABLE T_CT_COLABORACAO
    ADD CONSTRAINT FK_CT_COLABORACAO_USUARIO FOREIGN KEY
    (
     CD_USUARIO
    )
    REFERENCES T_CT_USUARIO
    (
     CD_USUARIO
    )
;

ALTER TABLE T_CT_MENSAGEM
    ADD CONSTRAINT FK_CT_MENSAGEM_PROJETO FOREIGN KEY
    (
     CD_PROJETO
    )
    REFERENCES T_CT_PROJETO
    (
     CD_PROJETO
    )
;

ALTER TABLE T_CT_MENSAGEM
    ADD CONSTRAINT FK_CT_MENSAGEM_USUARIO FOREIGN KEY
    (
     CD_USUARIO
    )
    REFERENCES T_CT_USUARIO
    (
     CD_USUARIO
    )
;

ALTER TABLE T_CT_PROJETO
    ADD CONSTRAINT FK_CT_PROJETO_USUARIO FOREIGN KEY
    (
     CD_USUARIO
    )
    REFERENCES T_CT_USUARIO
    (
     CD_USUARIO
    )
;

ALTER TABLE T_CT_TAREFA
    ADD CONSTRAINT FK_CT_TAREFA_PROJETO FOREIGN KEY
    (
     CD_PROJETO
    )
    REFERENCES T_CT_PROJETO
    (
     CD_PROJETO
    )
;

ALTER TABLE T_CT_USUARIO
ADD CONSTRAINT CK_CT_USUARIO_TIPO CHECK (TP_USUARIO IN ('ESTUDANTE', 'estudante', 'Estudante',
'PROFISSIONAL', 'profissional', 'Profissional', 'EMPRESA', 'empresa', 'Empresa'));

ALTER TABLE T_CT_TAREFA
ADD CONSTRAINT CK_CT_TAREFA_STATUS CHECK (DS_STATUS IN('INICIADA', 'iniciada', 'Iniciada',
'EM ANDAMENTO', 'em andamento', 'Em andamento', 'ENCERRADA', 'encerrada', 'Encerrada', 'ATIVA', 'ativa', 'Ativa'));

ALTER TABLE T_CT_AVALIACAO
ADD CONSTRAINT CK_CT_NOTA_AVALIACAO
CHECK (NT_AVALIACAO >= 0 AND NT_AVALIACAO <= 10);

ALTER TABLE T_CT_TAREFA
ADD CONSTRAINT CK_CT_TAREFA_CONCLUSAO CHECK ( DT_CONCLUSAO IS NULL  OR DT_CONCLUSAO >= DT_CRIACAO);

CREATE SEQUENCE SQ_CT_USUARIO NOCYCLE NOCACHE;
CREATE SEQUENCE SQ_CT_PROJETO NOCYCLE NOCACHE;
CREATE SEQUENCE SQ_CT_TAREFA NOCYCLE NOCACHE;
CREATE SEQUENCE SQ_CT_COLABORACAO NOCYCLE NOCACHE
CREATE SEQUENCE SQ_CT_MENSAGEM NOCYCLE NOCACHE
CREATE SEQUENCE SQ_CT_AVALIACAO NOCYCLE NOCACHE
